name: 'Deploy to Firebase Cloud Functions'
author: 'elingan <elingan@gmail.com>'
description: 'A GitHub Action to deploy to Firebase Cloud Functions (with Firebase environment configuration)'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'black'
